### PR TITLE
fixed weird search input when going back from moviepage - fixed #10

### LINKED ISSUE #10: Weird search input when i go back
Steps to reproduce:
- on the homepage of the app
- search for "back to the future"
- click on one of the entries in the list
- when on the single page view of the movie, click the back button

Expected results:
- the search bar to contain the input "back to the future"

Actual results:
- the search bar contains a weird text "back%20to%20the%20future"

### PR DESCRIPTION
**Pull request by alex1lazar**

### CODE REVIEW

File: src/app/customHttpParamDecoder.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import { HttpParameterCodec } from '@angular/common/http';
+
+export class CustomHttpParamEncoder implements HttpParameterCodec {
```
Comment (mikeddol) [inline src/app/customHttpParamDecoder.ts]: What is the point of this file? It seems to not be used anywhere in the application.

File: src/app/search-page/search-page.component.ts [hunk 2]
```diff
@@ -2,7 +2,8 @@ import { Component, OnInit } from '@angular/core';
 import { LocationStrategy } from '@angular/common';
 import { Movie } from '../movie';
 import { SearchBarComponent } from '../search-bar/search-bar.component';
-
+import { CustomHttpParamEncoder } from '../customHttpParamDecoder';
+import { HttpParameterCodec } from '@angular/common/http';
```
Comment (mikeddol) [inline src/app/search-page/search-page.component.ts]: Both these 2 libs are imported but not used anywhere.

File: src/app/search-bar/search-bar.component.ts [hunk 3]
```diff
@@ -1,6 +1,7 @@
 import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';
 import { SearchService } from '../search.service';
 import { Movie } from '../movie';
+import { CustomHttpParamEncoder } from '../customHttpParamDecoder';
```
Comment (mikeddol) [inline src/app/search-bar/search-bar.component.ts]: This is imported but not used.
