### PR TITLE
fixed problem when searching for an invalid title - fixed #11

### LINKED ISSUE #11: Nothing happens when i search for something
Steps to reproduce
- On the homepage of the app
- Try to search for "asfsdfadf"

Expected results:
- To be informed of either an error or nothing found (depending on case I guess?)

Actual results:
- Nothing happens.

### PR DESCRIPTION
**Pull request by alex1lazar**

### CODE REVIEW

File: src/app/search-bar/search-bar.component.ts [hunk 1]
```diff
@@ -21,8 +24,14 @@ export class SearchBarComponent implements OnInit {
   ngOnInit() { }
 
   public onEnter(enteredText: string): void {
-    this.searchService.getMovieTitle(enteredText).subscribe(movies => this.movies.emit(movies));
-    this.searchService.setSearchedText(enteredText);
+   this.searchService.getMovieTitle(enteredText).subscribe(response => {
+      if (response === 'Movie not found!') {
+        console.log('WRONG');
```
Comment (mikeddol) [inline src/app/search-bar/search-bar.component.ts]: What is the point of this?

File: src/app/search.service.ts [hunk 2]
```diff
@@ -12,13 +12,27 @@ export class SearchService {
   urlBySearch = 'http://www.omdbapi.com/?apikey=154db7cd&s=';
   ulrById = 'http://www.omdbapi.com/?apikey=154db7cd&i=';
   searchedText = '';
+  theBoolean = new BehaviorSubject<boolean>(false);
```
Comment (mikeddol) [inline src/app/search.service.ts]: This is not used anywhere

File: src/app/search.service.ts [hunk 3]
```diff
@@ -12,13 +12,27 @@ export class SearchService {
...
 
   constructor(private http: HttpClient) { }
 
-  public getMovieTitle(title: string): Observable<Movie[]> {
+  // public getMovieTitle(title: string): Observable<Movie[]> {
+  //   return this.http.get<any>(`${this.urlBySearch}${title}`)
+  //     .pipe(
+  //       map(response => response.Search.map(movie => new Movie(movie)))
```
Comment (mikeddol) [inline src/app/search.service.ts]: Is this still used? We shouldn't have commented out code.
